-- Create the comments table
create table comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  content text not null,
  likes bigint default 0
);

-- Set up Row Level Security (RLS)
alter table comments enable row level security;

-- Create policy to allow anyone to read comments
create policy "Public comments are viewable by everyone"
  on comments for select
  using ( true );

-- Create policy to allow anyone to insert comments (you might want to restrict this in production)
create policy "Anyone can insert comments"
  on comments for insert
  with check ( true );
